apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: db-deployment
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
