apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: frontend
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: kaputinho/basic3tier-front
        name: frontend
        ports:
          - containerPort: 80
            name: frontend
