apiVersion: v1
kind: Service
metadata: 
  name: db-service-clusterip
  namespace: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
